### ISSUE TITLE
fails to work on github actions

### ISSUE THREAD

**Issue by pseudozach** [benyap/firestore-backfire#239]
Hi, I'm trying to automatically export a db and make it available publicly, so I tried to add this to github actions but it failed with below error.

>npm ERR! could not determine executable to run

this is what I used, any reason why it shouldn't work?

```
name: Backup Firestore
on: [push]
  jobs:
  backup:
    runs-on: ubuntu-latest
    steps:
    - name: Create secret files
      run: |
        echo ${{ secrets.GCP_SA_KEY }} | base64 -d > gcp.json
        echo ${{ secrets.FB_SA_KEY }} | base64 -d > fb.json
        
    - name: Backup firestore db in json format
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
      run: npx backfire export gs://nostrdb-backups  --gcpProject nostrdirectory --gcpKeyFile gcp.json --paths twitter --project nostrdirectory --keyFile fb.json
```
